name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add aarch64-linux-android

      - name: Install Android NDK
        uses: nttld/setup-ndk@v2
        with:
          ndk-version: r27c
          add-to-path: true

      - name: Set up environment
        run: |
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang" >> $GITHUB_ENV
          echo "CC_aarch64_linux_android=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang" >> $GITHUB_ENV
          echo "AR_aarch64_linux_android=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" >> $GITHUB_ENV

      - name: Build dynamically linked binary
        run: |
          cargo build --release --target aarch64-linux-android
          mv target/aarch64-linux-android/release/test test-dynamic

      - name: Build statically linked binary
        run: |
          # Static linking with NDK's crt_static
          export RUSTFLAGS="-C target-feature=+crt-static"
          cargo build --release --target aarch64-linux-android
          mv target/aarch64-linux-android/release/test test-static

      - name: Verify binaries
        run: |
          file test-dynamic
          file test-static
          readelf -d test-dynamic | grep NEEDED
          readelf -d test-static | grep NEEDED || echo "Static binary has no dynamic dependencies"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-binaries
          path: |
            test-dynamic
            test-static
